// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbLayer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	Username   string
	Passwdhash string
	Powerlevel int32
	Firstname  string
	Lastname   string
	Email      string
	Valid      pgtype.Bool
}

type Bearertoken struct {
	Tokenstring string
	Validtill   pgtype.Timestamp
	Username    string
	Valid       pgtype.Bool
}
